### ISSUE TITLE
direct analysis server.conf

### ISSUE THREAD

**Issue by originnets** [aluttik/go-crossplane#6]
server {
  listen       127.0.0.1:8080;
  server_name www.test.com test.com;
  index index.html index.htm;
}

How to parse the file directly

**Comment by aluttik** [comment]
```go
payload, err := crossplane.Parse("path/to/server.conf", &crossplane.ParseOptions{})
```
This should give you a `Payload` struct that has the parsed content.

Does this answer your question?
